# name : python file skeleton w/class declaration
# contributor: Steen Manniche <steen@manniche.net>
# provides a skeleton python file template, with docstrings and a class definition
# --
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
"""@module `(substring (file-name-sans-extension (buffer-name)) 0 -2)`
$(1:module purpose)
"""

class ${1:class name}( ${2:object} ):
    """ $1

    """
    def __init__( self ${3:, arg} ):
        """$4

        """
        $0
