#!/usr/bin/env bash
export NO_AT_BRIDGE=1
mate-settings-daemon &
/usr/bin/wmname LG3D &
nm-applet 2>/dev/null &
mate-power-manager &
volti &
/usr/bin/SpiderOakONE &
xmodmap ~/.Xmodmap
setxkbmap -option ctrl:nocaps
synclient MaxTapTime=0
feh --bg-fill .i3/deep-dark-space.png
